components:
    serializers:
        BasicConfig:
            type: object
            properties:
                id:
                    type: integer
                    example: 1
                name:
                    type: string
                    example: config 1
                gameMode:
                    type: string
                    example: SUPREMACY
                isPrivate:
                    type: boolean
                    example: false
                createdAt:
                    type: string
                    format: date-time
                    example: 2020-02-10T17:04:24.000Z
        CreatedConfig:
            type: object
            properties:
                id:
                    type: integer
                    example: 1
                name:
                    type: string
                    example: config 1
                isPrivate:
                    type: boolean
                    example: false
                maxPlayers:
                    type: integer
                    example: 10
                gameMode:
                    type: string
                    example: FLAG
                duration:
                    type: integer
                    example: 600
                inventorySize:
                    type: integer
                    example: 7
                createdAt:
                    type: string
                    format: date-time
                    example: 2020-02-10T17:04:24.000Z
                OwnerId:
                    type: integer
                    example: 1
        DetailedConfig:
            type: object
            properties:
                id:
                    type: integer
                    example: 1
                name:
                    type: string
                    example: config 1
                isPrivate:
                    type: boolean
                    example: false
                maxPlayers:
                    type: integer
                    example: 10
                gameMode:
                    type: string
                    example: FLAG
                duration:
                    type: integer
                    example: 600
                inventorySize:
                    type: integer
                    example: 7
                createdAt:
                    type: string
                    format: date-time
                    example: 2020-02-10T17:04:24.000Z
                OwnerId:
                    type: integer
                    example: 1
                Owner:
                    type: object
                    properties:
                        username:
                            type: string
                            example: clement284
