version: "3.5"
services:
  node:
    container_name: serveur_jeu
    build:
      context: ./
      dockerfile: ./serveur_jeu/Dockerfile
      args:
        port: "${port_node}"
    volumes:
      - ./config:/config
    ports:
      - "${port_node}:${port_node}"
    networks:
      static-network:
        ipv4_address: "172.20.35.40"

  react:
    container_name: client_web_maitre
    build:
      context: ./
      dockerfile: ./client_maitre/Dockerfile
      args:
        port: "${port_react}"
        port_serveur: "${port_node}"
    volumes:
      - ./config:/config
    ports:
      - "${port_react}:${port_react}"
    networks:
      static-network:
        ipv4_address: "172.20.40.50"
    stdin_open: true

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
